package constants

// 日志模板（≥25 条，集中定义；业务字段变更必须同步修改对应模板与调用处）。
const (
	LogUserRegisterStart   = "user register start: username=%s"
	LogUserRegisterOK      = "user register success: username=%s role=%s"
	LogUserLoginOK         = "user login success: username=%s role=%s"
	LogUserLoginFail       = "user login failed: username=%s reason=%s"
	LogTokenIssue          = "jwt token issued: user_id=%d username=%s"
	LogPaperCreateStart    = "paper create start: submitter_id=%d title=%s"
	LogPaperCreateOK       = "paper create success: paper_id=%d status=%s"
	LogPaperUpdateOK       = "paper update success: paper_id=%d"
	LogPaperDetail         = "paper detail fetched: paper_id=%d role=%s"
	LogPaperList           = "paper list fetched: role=%s status=%s page=%d"
	LogInitialReviewOK     = "initial review done: paper_id=%d passed=%t reviewer_id=%d"
	LogInitialReviewReject = "initial review rejected: paper_id=%d reason=%s"
	LogAssignReviewer      = "reviewer assigned: paper_id=%d reviewer_id=%d"
	LogReviewRespond       = "review respond: review_id=%d reviewer_id=%d accept=%t"
	LogReviewSubmit        = "review submitted: review_id=%d decision=%s"
	LogReviewList          = "review list fetched: reviewer_id=%d status=%s"
	LogReviseSubmit        = "revision submitted: paper_id=%d version=%d"
	LogFinalDecision       = "final decision made: paper_id=%d decision=%s"
	LogPlagiarismRun       = "plagiarism check run: paper_id=%d similarity=%.2f"
	LogPlagiarismAutoReject = "plagiarism auto reject: paper_id=%d similarity=%.2f"
	LogFileUploadOK        = "file upload success: key=%s size=%d"
	LogAuditRecord         = "audit record written: action=%s entity=%s entity_id=%s"
	LogAuditList           = "audit list fetched: page=%d size=%d"
	LogStatsOverview       = "statistics overview computed"
	LogStatsTrend          = "statistics trend computed: days=%d"
	LogStatsSubjects       = "statistics subject distribution computed"
	LogStatsReviewers      = "statistics reviewer workload computed"
	LogRateLimited         = "rate limited: ip=%s"
	LogRequestStart        = "request start: method=%s path=%s request_id=%s"
	LogRequestDone         = "request done: method=%s path=%s status=%d latency_ms=%d"
	LogProfileUpdate       = "user profile updated: user_id=%d"
	LogPlagiarismGet       = "plagiarism result fetched: paper_id=%d"
)
